[build]
builder = "nixpacks"

[build.nixpacksConfig]
installCmd = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "$PORT"
NPM_CONFIG_PRODUCTION = "false"